### PR TITLE
Copy latest changelog to respective device folder

### PR DESCRIPTION
**Pull request by chdelacr**
Added confirmation messages, copy operation and updated notes for OTA script.  This is OK for OTA repo under the ROM directory, but that's just a suggestion.

### CODE REVIEW

**Comment by chdelacr** [comment]
It should be easier now to update any path reference in the script, and the OTADIR variable will be used to copy the changelog to the appropriate OTA repo path (and show cool log messages with paths).

**Review by darkbeast69 — CHANGES_REQUESTED** [review]
Changelog file should be formatted like .zip.txt

**Comment by chdelacr** [comment]
> Changelog file should be formatted like .zip.txt

Do you mean renaming the changelog file from .txt to .zip.txt?

**Comment by darkbeast69** [comment]
> > Changelog file should be formatted like .zip.txt
> 
> Do you mean renaming the changelog file from .txt to .zip.txt?

Yes .....

**Comment by chdelacr** [comment]
@darkbeast69 Question, isn't easier to name the txt file like that by updating the script that creates the txt file? I don't know what that file is, but I'd like to make sure

**Pull request closed without merging**
